spring:
  application:
    name: departamento-service
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: departamentos;
#      port: 27017
#      host: localhost   
server:
  # port: ${PORT:0}
  port: 7777
app:
  helloServiceUrl: http://localhost:30000/saluda/
  empleadosServiceUrl: http://localhost:31000/empleados/
  empleadosServiceAlias: empleado-service
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    # Generamos id aleatorio para poder registrar diferentes instancias con eureka
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

